rooms:
  - id: none
    name: "General"
    icon: "home"
  - id: master_bedroom
    icon: "bed"
  - id: study
    icon: "books"
  - id: living_room
    icon: "lamp"
  - id: meter_cabinet
    icon: "server-alt"
  - id: corridor
  - id: hallway
    icon: "archway"
  - id: bathroom
    icon: "bath"
  - id: kitchen
    icon: "restaurant"

characteristics:
  - id: temperature
    source: voltage
    type: numeric
    range:
      min: 0
      max: 40
    decimals: 0
    unit: "℃"
    writable: false
  - id: on
    name: "status"
    type: binary
    writable: true
  - id: binary_input
    name: "status"
    source: on
    type: binary
    writable: false
  - id: activity
    source: on
    type: binary
    writable: false
  - id: analog_activity
    source: voltage
    type: binary
    writable: false
  - id: open_closed
    source: on
    name: "status"
    type: binary
    values:
      off: closed
      on: open
    states:
      on: danger
  - id: brightness
    type: numeric
    range:
      min: 0
      max: 254
    unit: "%"
    writable: true
  - id: hue_sensor_battery_level
    source: battery_level
    type: numeric
    range:
      min: 0
      max: 100
    unit: "%"
    writable: false
  - id: hue_dimmer_button
    source: button
    type: string
    writable: false
  - id: hue_dimmer_button_event
    source: button_event
    type: string
    writable: false
  - id: hue_dimmer_button_event_description
    source: description
    type: string
    writable: false

interfaces:
  - id: meter_cabinet_eth
    type: devantech_eth
    host: 192.168.1.114
    port: 17123
    polling_interval: 1000
  - id: hue_bridge
    type: hue
    host: 192.168.1.144
    polling_interval: 1000
    config:
      username: <%= System.get_env("HUE_USERNAME") %>

device_types:
  - id: eth_temperature
    connection: devantech_eth_analogue_input
    config:
      voltage_range:
        min: 0
        max: 1.75
      value_range:
        min: -50
        max: 125
    characteristics: [temperature]
    icon: "temperature-half"
  - id: eth_light
    connection: devantech_eth_relay
    characteristics: [on]
    icon: "lightbulb"
  - id: eth_outlet
    connection: devantech_eth_relay
    characteristics: [on]
    icon: "plug"
  - id: eth_motion_sensor
    connection: devantech_eth_analogue_input
    characteristics: [analog_activity]
    icon: "webcam"
    config:
      voltage_range:
        min: 0
        max: 3.3
      value_range:
        min: 0
        max: 1
  - id: eth_window
    connection: devantech_eth_digital_input
    characteristics: [open_closed]
    icon: "lock-open-alt"
  - id: eth_digital_input
    connection: devantech_eth_digital_input
    characteristics: [binary_input]
    icon: "eye"
  - id: eth_switch
    connection: devantech_eth_relay
    characteristics: [on]
    icon: power
  - id: eth_doorbell
    connection: devantech_eth_digital_input
    characteristics: [activity]
    icon: "bell"
  - id: hue_go
    connection: hue_go
    characteristics: [on, brightness]
    icon: "lightbulb"
  - id: hue_dimmable_light
    connection: hue_dimmable_light
    characteristics: [on, brightness]
    icon: "lightbulb"
  - id: hue_outlet
    connection: hue_outlet
    characteristics: [on]
    icon: "plug"
  - id: hue_daylight_sensor
    connection: hue_daylight_sensor
    characteristics: [binary_input]
    icon: "sun"
  - id: hue_dimmer_switch
    connection: hue_dimmer_switch
    characteristics:
    - hue_dimmer_button_event_description
    - hue_dimmer_button_event
    - hue_dimmer_button
    - hue_sensor_battery_level
    icon: "sliders-v-alt"

devices:
  - id: meter_cabinet_temperature
    type: eth_temperature
    room: meter_cabinet
    interface: meter_cabinet_eth
    pin: 1
  - id: meter_cabinet_relay_1
    type: eth_outlet
    room: meter_cabinet
    interface: meter_cabinet_eth
    pin: 1
  - id: meter_cabinet_motion_sensor
    type: eth_motion_sensor
    room: meter_cabinet
    interface: meter_cabinet_eth
    pin: 2
  - id: meter_cabinet_input_1
    type: eth_digital_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    pin: 1
  - id: meter_cabinet_input_3
    type: eth_digital_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    pin: 3
  - id: meter_cabinet_input_4
    type: eth_digital_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    pin: 4
  - id: doorbell_switch
    type: eth_switch
    room: none
    interface: meter_cabinet_eth
    pin: 32
  - id: doorbell
    type: eth_doorbell
    room: none
    interface: meter_cabinet_eth
    pin: 2
  - id: study_hue_go
    type: hue_go
    room: study
    interface: hue_bridge
    pin: 9
  - id: living_room_light
    type: hue_dimmable_light
    room: living_room
    interface: hue_bridge
    pin: 2
  - id: corridor_light
    type: hue_dimmable_light
    room: corridor
    interface: hue_bridge
    pin: 7
  - id: bathroom_light
    type: hue_dimmable_light
    room: bathroom
    interface: hue_bridge
    pin: 8
  - id: kitchen_table_light_1
    type: hue_dimmable_light
    room: kitchen
    interface: hue_bridge
    pin: 19
  - id: kitchen_table_light_2
    type: hue_dimmable_light
    room: kitchen
    interface: hue_bridge
    pin: 20
  - id: kitchen_table_light_3
    type: hue_dimmable_light
    room: kitchen
    interface: hue_bridge
    pin: 21
  - id: kitchen_table_light_4
    type: hue_dimmable_light
    room: kitchen
    interface: hue_bridge
    pin: 22
  - id: kitchen_table_light_5
    type: hue_dimmable_light
    room: kitchen
    interface: hue_bridge
    pin: 23
  - id: kitchen_table_light_6
    type: hue_dimmable_light
    room: kitchen
    interface: hue_bridge
    pin: 24
  - id: hallway_light
    type: hue_dimmable_light
    room: hallway
    interface: hue_bridge
    pin: 16
  - id: tv_outlet
    type: hue_outlet
    room: living_room
    interface: hue_bridge
    pin: 17
  - id: kitchen_counter_lights
    type: hue_outlet
    room: kitchen
    interface: hue_bridge
    pin: 18
  - id: daylight
    type: hue_daylight_sensor
    room: none
    interface: hue_bridge
    pin: 1
  - id: hue_dimmer_switch
    type: hue_dimmer_switch
    room: none
    interface: hue_bridge
    pin: 2

groups:
  - id: kitchen_table_lights
    room: kitchen
    icon: "lightbulb"
    devices:
    - kitchen_table_light_1
    - kitchen_table_light_2
    - kitchen_table_light_3
    - kitchen_table_light_4
    - kitchen_table_light_5
    - kitchen_table_light_6
  - id: upstairs_lights
    room: none
    icon: "lightbulb"
    devices:
    - corridor_light
    - bathroom_light
  - id: study_lights
    room: study
    icon: "lightbulb"
    devices:
    - study_hue_go

notifiers:
  - id: slack
    interface: http
    config:
      url: |
        <%= System.get_env("SLACK_WEBHOOK") %>
      method: post
      content_type: json
      body: '{"text": "<%= message %>"}'

automations:
  - id: doorbell_slack_notification
    event: activated
    subject: doorbell
    characteristic: on
    actions:
    - action: notify
      target: slack
      config:
        message: "🔔🔔 @here Someone's at the door 🔔🔔"
    - action: blink
      target: living_room_light
    - action: blink
      target: study_hue_go
  - id: doorbell_turn_on_hallway_light
    event: activated
    subject: doorbell
    characteristic: on
    action: activate
    target: hallway_light
  - id: evening_turn_off_doorbell
    event: time
    value: 19:00
    action: deactivate
    target: doorbell_switch
  - id: morning_turn_on_doorbell
    event: time
    value: 7:00
    action: activate
    target: doorbell_switch
  - id: sunrise_turn_off_lights
    event: activated
    subject: daylight
    characteristic: on
    actions:
    - action: deactivate
      target: kitchen_table_lights
    - action: deactivate
      target: kitchen_counter_lights
    - action: deactivate
      target: living_room_light
    - action: deactivate
      target: hallway_light
    - action: deactivate
      target: upstairs_lights
  - id: sunset_turn_on_lights
    event: deactivated
    subject: daylight
    characteristic: on
    actions:
    - action: activate
      target: kitchen_table_lights
    - action: activate
      target: kitchen_counter_lights
    - action: activate
      target: living_room_light
  - id: turn_on_kitchen_table_lights_with_hue_remote
    event: state
    subject: hue_dimmer_switch
    characteristic: button
    value: 2
    action: activate
    target: kitchen_table_lights
  - id: turn_off_kitchen_table_lights_with_hue_remote
    event: state
    subject: hue_dimmer_switch
    characteristic: button
    value: 3
    action: deactivate
    target: kitchen_table_lights
