rooms:
  - id: none
    name: "General"
    icon: "home"
  - id: master_bedroom
    icon: "bed"
  - id: study
    icon: "books"
  - id: living_room
    icon: "lamp"
  - id: meter_cabinet
    icon: "server-alt"
  - id: corridor
  - id: hallway
    icon: "archway"
  - id: bathroom
    icon: "bath"
  - id: kitchen
    icon: "restaurant"

interfaces:
  - id: meter_cabinet_eth
    type: devantech_eth
    host: 192.168.1.114
    port: 17123
    polling_interval: 1000
  - id: hue_bridge
    type: hue
    host: 192.168.1.145
    polling_interval: 1000
    config:
      username: <%= System.get_env("HUE_USERNAME") %>
  - id: watcher_rpi_1
    type: mqtt_io
    host: homeapp.home
    port: 1883
    config:
      topic: home/input/#
  - id: smoov
    type: smoov
    polling_interval: 60000
  - id: home_network
    type: network_discovery
    polling_interval: 60000
    config:
      ip_range: 192.168.1.0/24
  - id: acv_calendar
    type: waste_calendar
    polling_interval: 3600000
    config:
      company_code: f8e2844a-095e-48f9-9f98-71fceb51d2c3
  - id: epex_prices
    type: cheap_energy
    polling_interval: 3600000
    config:
      token: <%= System.get_env("ENTSOE_TOKEN") %>

devices:
  - id: cheap_energy_dryer
    type: cheap_energy_cheap_hours
    room: none
    interface: epex_prices
    config:
      consecutive: true
      hours: 3
  - id: acv_waste_calendar
    type: waste_calendar_waste_calendar
    room: none
    interface: acv_calendar
    config:
      post_code: <%= System.get_env("ZIP_CODE") %>
      house_number: <%= System.get_env("HOUSE_NUMBER") %>
  - id: charge_point_home
    type: smoov_charge_point
    room: none
    interface: smoov
    config:
      id: NLALLEGO013429
  - id: iphone_martijn
    type: network_discovery_network_device
    interface: home_network
    room: none
    config:
      mac_address: fa:97:e2:b6:69:38
  - id: work_phone_charlotte
    type: network_discovery_network_device
    interface: home_network
    room: none
    config:
      mac_address: 3a:a1:f8:32:73:4a
  - id: macbook_martijn
    type: network_discovery_network_device
    interface: home_network
    room: none
    config:
      mac_address: f4:d4:88:73:95:b8
  - id: mqtt_io_test_port
    type: mqtt_io_digital_input
    room: meter_cabinet
    interface: watcher_rpi_1
    monitor_hold: true
    config:
      pin: 21
  - id: meter_cabinet_temperature
    type: devantech_eth_analogue_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    config:
      pin: 1
      voltage_range:
        min: 0
        max: 1.75
      value_range:
        min: -50
        max: 125
      decimals: 0
  - id: meter_cabinet_relay_1
    type: devantech_eth_relay
    room: meter_cabinet
    interface: meter_cabinet_eth
    config:
      pin: 1
  - id: meter_cabinet_motion_sensor
    type: devantech_eth_analogue_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    config:
      pin: 2
      voltage_range:
        min: 0
        max: 3.3
      value_range:
        min: 0
        max: 1
  - id: meter_cabinet_input_1
    type: devantech_eth_digital_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    monitor_hold: true
    config:
      pin: 1
  - id: meter_cabinet_input_3
    type: devantech_eth_digital_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    config:
      pin: 3
  - id: meter_cabinet_input_4
    type: devantech_eth_digital_input
    room: meter_cabinet
    interface: meter_cabinet_eth
    config:
      pin: 4
  - id: doorbell_switch
    type: devantech_eth_relay
    room: none
    interface: meter_cabinet_eth
    config:
      pin: 32
  - id: doorbell
    type: devantech_eth_relay
    room: none
    interface: meter_cabinet_eth
    config:
      pin: 2
  - id: study_hue_go
    type: hue_go
    room: study
    interface: hue_bridge
    config:
      id: 9
  - id: living_room_light
    type: hue_light
    room: living_room
    interface: hue_bridge
    config:
      id: 2
  - id: corridor_light
    type: hue_light
    room: corridor
    interface: hue_bridge
    config:
      id: 7
  - id: bathroom_light
    type: hue_light
    room: bathroom
    interface: hue_bridge
    config:
      id: 8
  - id: kitchen_table_light_1
    type: hue_light
    room: kitchen
    interface: hue_bridge
    config:
      id: 19
  - id: kitchen_table_light_2
    type: hue_light
    room: kitchen
    interface: hue_bridge
    config:
      id: 20
  - id: kitchen_table_light_3
    type: hue_light
    room: kitchen
    interface: hue_bridge
    config:
      id: 21
  - id: kitchen_table_light_4
    type: hue_light
    room: kitchen
    interface: hue_bridge
    config:
      id: 22
  - id: kitchen_table_light_5
    type: hue_light
    room: kitchen
    interface: hue_bridge
    config:
      id: 23
  - id: kitchen_table_light_6
    type: hue_light
    room: kitchen
    interface: hue_bridge
    config:
      id: 24
  - id: hallway_light
    type: hue_light
    room: hallway
    interface: hue_bridge
    config:
      id: 16
  - id: tv_outlet
    type: hue_outlet
    room: living_room
    interface: hue_bridge
    config:
      id: 17
  - id: kitchen_counter_lights
    type: hue_outlet
    room: kitchen
    interface: hue_bridge
    config:
      id: 18
  - id: daylight
    type: hue_daylight_sensor
    room: none
    interface: hue_bridge
    config:
      id: 1
  - id: hue_dimmer_switch
    type: hue_dimmer_switch
    room: none
    interface: hue_bridge
    config:
      id: 2

groups:
  - id: kitchen_table_lights
    room: kitchen
    icon: "lightbulb"
    devices:
    - kitchen_table_light_1
    - kitchen_table_light_2
    - kitchen_table_light_3
    - kitchen_table_light_4
    - kitchen_table_light_5
    - kitchen_table_light_6
  - id: upstairs_lights
    room: none
    icon: "lightbulb"
    devices:
    - corridor_light
    - bathroom_light
  - id: study_lights
    room: study
    icon: "lightbulb"
    devices:
    - study_hue_go

notifiers:
  - id: slack
    interface: http
    config:
      url: |
        <%= System.get_env("SLACK_WEBHOOK") %>
      method: post
      content_type: json
      body: '{"text": "<%%= message %>"}'

automations:
  - id: doorbell_slack_notification
    event: activated
    subject: doorbell
    characteristic: on
    actions:
    - action: notify
      target: slack
      config:
        message: "🔔🔔 @here Someone's at the door 🔔🔔"
    - action: blink
      target: living_room_light
    - action: blink
      target: study_hue_go
  - id: doorbell_turn_on_hallway_light
    event: activated
    subject: doorbell
    characteristic: on
    action: activate
    target: hallway_light
  - id: evening_turn_off_doorbell
    event: time
    value: 19:00
    action: deactivate
    target: doorbell_switch
  - id: morning_turn_on_doorbell
    event: time
    value: 7:00
    action: activate
    target: doorbell_switch
  - id: sunrise_turn_off_lights
    event: activated
    subject: daylight
    characteristic: on
    actions:
    - action: deactivate
      target: kitchen_table_lights
    - action: deactivate
      target: kitchen_counter_lights
    - action: deactivate
      target: living_room_light
    - action: deactivate
      target: hallway_light
    - action: deactivate
      target: upstairs_lights
  - id: sunset_turn_on_lights
    event: deactivated
    subject: daylight
    characteristic: on
    actions:
    - action: activate
      target: kitchen_table_lights
    - action: activate
      target: kitchen_counter_lights
    - action: activate
      target: living_room_light
  - id: turn_on_kitchen_table_lights_with_hue_remote
    event: state
    subject: hue_dimmer_switch
    characteristic: button
    value: 2
    action: activate
    target: kitchen_table_lights
  - id: turn_off_kitchen_table_lights_with_hue_remote
    event: state
    subject: hue_dimmer_switch
    characteristic: button
    value: 3
    action: deactivate
    target: kitchen_table_lights
